# NUMPY

In [71]:
import numpy as np


In [72]:
a=[1,2,3,4.5,'h',"hello"]
a

[1, 2, 3, 4.5, 'h', 'hello']

In [73]:
np.array(a)  # all string

array(['1', '2', '3', '4.5', 'h', 'hello'], dtype='<U32')

In [74]:
l=[[1,2,3],[5,6,7],[9,10,8]]
l

[[1, 2, 3], [5, 6, 7], [9, 10, 8]]

In [75]:
np.array(l)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10,  8]])

In [76]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [78]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [79]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
np.linspace(1,10,5)  #even distribution

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [82]:
np.random.rand(10) # 0-1 normalization

array([0.98436634, 0.1498915 , 0.55840131, 0.23111175, 0.12526138,
       0.48122898, 0.88568808, 0.26288864, 0.421309  , 0.63460714])

In [83]:
np.random.randn(10) #  -3 to 3 standardalization

array([-0.30240396,  0.7493012 ,  0.15719578, -0.00878672,  0.89058259,
       -1.02888876, -1.15158668, -0.33688018, -0.66587188,  1.30841415])

In [84]:
np.random.randint(5)

3

In [85]:
np.random.randint(5,10)

8

# **Array**

In [86]:
arr=np.array([[1,2,3],[4,50,6],[7,8,9]])
arr

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

# Array Attributes

In [87]:
arr.size

9

In [88]:
arr.shape

(3, 3)

# Array Methods

In [89]:
arr.min()

np.int64(1)

In [90]:
arr.max()

np.int64(50)

In [91]:
arr.sum()

np.int64(90)

In [92]:
np.sum(arr,axis=0)  #row wise

array([12, 60, 18])

In [93]:
np.sum(arr,axis=1) #coloum wise

array([ 6, 60, 24])

In [94]:
arr.mean()

np.float64(10.0)

In [95]:
arr.std()

np.float64(14.375905768565216)

In [96]:
arr.argmax() # max element er index

np.int64(4)

# Reshape an Resize

In [97]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [98]:
arr = arr.reshape(5,6) #must check number of element fits in shpae
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

# Indexing and Slicing of Vector

In [99]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [100]:
arr[9]

np.int64(10)

In [101]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [102]:
arr[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# Indexing and Slicing of Matrix

In [103]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [104]:
arr = arr.reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [105]:
arr[0] # print rows

array([1, 2, 3, 4, 5])

In [106]:
arr[:,2:3] #print coloumn

array([[ 3],
       [ 8],
       [13],
       [18]])

In [107]:
arr[:,2]  #print coloumn

array([ 3,  8, 13, 18])

In [108]:
arr[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [109]:
arr[1:,3:]

array([[ 9, 10],
       [14, 15],
       [19, 20]])

# Boolean Indexing

In [110]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [111]:
bool_idx = arr%2 == 0
bool_idx

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [112]:
arr = arr[bool_idx]
arr

array([12, 14, 16, 18, 20])

# Array Operations

In [113]:
a1=np.array([1,2,3,4,5])
a2=np.array([1,2,3,4,5])

In [114]:
a1+a2

array([ 2,  4,  6,  8, 10])

In [115]:
a1-a2

array([0, 0, 0, 0, 0])

In [116]:
a1*a2

array([ 1,  4,  9, 16, 25])

# Broadcasting

In [117]:
a1+10

array([11, 12, 13, 14, 15])

In [118]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
b=a  # deep copy
b
b[0]=90
a

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
b=a.copy()  # swallo copy
b[0]=90
a

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Matrix Operations

In [121]:
A = np.arange(1,21).reshape(5,4)
B = np.arange(21,41).reshape(4,5)
A,  B

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]]))

In [122]:
A @ B # Multiplication

array([[ 310,  320,  330,  340,  350],
       [ 766,  792,  818,  844,  870],
       [1222, 1264, 1306, 1348, 1390],
       [1678, 1736, 1794, 1852, 1910],
       [2134, 2208, 2282, 2356, 2430]])

In [123]:
np.dot(A,B)  # dot multiplication

array([[ 310,  320,  330,  340,  350],
       [ 766,  792,  818,  844,  870],
       [1222, 1264, 1306, 1348, 1390],
       [1678, 1736, 1794, 1852, 1910],
       [2134, 2208, 2282, 2356, 2430]])

In [124]:
np.transpose(A) # Transpose

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

In [125]:
A.T # Transpose

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

# Array Manipulation: Stacking

In [126]:
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])

In [127]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [128]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [129]:
np.hstack((a,b))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [130]:
np.column_stack((a,b))

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

# Array Spliting

In [131]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [132]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [133]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# Exersises:

In [134]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

type(s)

numpy.ndarray

In [135]:
np.sum(s,axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [136]:
np.sum(s,axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [137]:
arr = s[0:3,0:3]
arr

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [138]:
for i in range(0,9,3):
  for j in range(0,9,3):
    # print(s[i:i+3,j:j+3])
    a = s[i:i+3,j:j+3]
    print(a.sum())

45
45
45
45
45
45
45
45
45


In [139]:
data = np.arange(1,16).reshape(3,5).T
data

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [140]:
data[data[:,2]==13]
# data[2,2]
data[data[:,2]==13,2]=0



data

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8,  0],
       [ 4,  9, 14],
       [ 5, 10, 15]])